### ISSUE TITLE
Documentação

### ISSUE THREAD

**Issue by ViniciusHass** [Treinamento-Stefa-IA-DevOps/treinamento-dia-04-08-vitorrangelcs#1]
https://github.com/Treinamento-Stefa-IA-DevOps/treinamento-dia-04-08-vitorrangelcs/blob/5cba53233f120de3b8fb7ce63967fef21463c7b0/tarefa/codigo/main.py#L19

Boa tarde @vitorrangelcs  **Vitor Rangel**,

Verifique na documentação o que é esperado de resposta.

**Comment by vitorrangelcs** [comment]
Obrigado pelo feedback @ViniciusHass
